import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import localFont from 'next/font/local';
import "../globals.css";
import Navbar from '../../components/Navbar/Navbar';
import Footer from '@/components/MyFooter';
import CookieConsentBanner from '../../components/CookieConsentBanner';
import ClientLayout from './ClientLayout';
import { ThemeProvider } from '../theme-provider'; // 导入 ThemeProvider

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children, params }) {
  const locale = params.locale || 'en';
  const messages = await getMessages(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans bg-background text-foreground dark:bg-darkBackground`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Navbar params={params} />
            <ClientLayout locale={locale}>
              <main>{children}</main>
            </ClientLayout>
            <CookieConsentBanner />
            <Footer className="text-center p-4 mt-8 border-t border-[#4a5c4d]">
            </Footer>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}