import { NextIntlClientProvider } from 'next-intl';  // 引入国际化上下文提供者
import { getMessages } from 'next-intl/server';      // 从服务端获取翻译消息
import localFont from 'next/font/local';
import "../globals.css"; // 引用全局样式
import Navbar from '../../components/Navbar/Navbar'; // 引用导航栏
import Footer from '@/components/MyFooter';
import CookieConsentBanner from '../../components/CookieConsentBanner'; // 引用Cookie同意弹框
import ClientLayout from './ClientLayout'; // 引用客户端布局

// 定义字体并使用绝对路径从 public 目录引用字体文件
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",  // 引用 public/fonts 目录中的文件
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",  // 引用 public/fonts 目录中的文件
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 页面元数据，只适用于服务器组件
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 服务器组件
export default async function Layout({ children, params }) {
  const locale = params.locale || 'en';
  const messages = await getMessages(locale);

  return (
    <html locale={locale}>
      <body className="bg-[#f3f2e9]">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className='w-full h-8 bg-[#151515]' ></div>
          <Navbar params={params} />
          <ClientLayout locale={locale}>
            <main>{children}</main>
          </ClientLayout>
          <CookieConsentBanner />
          <Footer className="text-center p-4 mt-8 border-t border-[#4a5c4d]">
          </Footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
