import { NextIntlClientProvider } from 'next-intl';  // 引入国际化上下文提供者
import { getMessages } from 'next-intl/server';      // 从服务端获取翻译消息
import localFont from 'next/font/local';
import "../globals.css"; // 引用全局样式
import Navbar from '../../components/Navbar/Navbar'; // 引用导航栏
import CookieConsentBanner from '../../components/CookieConsentBanner'; // 引用Cookie同意弹框

// 定义字体并使用绝对路径从 public 目录引用字体文件
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",  // 引用 public/fonts 目录中的文件
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",  // 引用 public/fonts 目录中的文件
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 页面元数据，只适用于服务器组件
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 布局组件
export default async function Layout({ children, params }) {
  const locale = params.lang || 'en';
  const messages = await getMessages(locale);

  return (
    <html lang={locale}>
      <body className="bg-[#f3f2e9]">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar params={params} />
          <main>{children}</main>
          <CookieConsentBanner />
          <footer className="text-center p-4 mt-8 border-t border-[#4a5c4d]">
            <p className="text-[#4a5c4d]">&copy; 2024 Sampola</p>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
